### ISSUE TITLE
How to change or disable hotkey？

### ISSUE THREAD

**Issue by samandachen** [fibo/flow-view#47]
i want to change or disable hotkey。How to change or disable hotkey？

**Comment by fibo** [comment]
It is not possible with current implementation to do it with a configuration flag. You should fork and use a custom Frame.js component with empty [onDocumentKeydown](https://github.com/fibo/flow-view/blob/master/src/components/Frame.js#L458) and [onDocumentKeyup](https://github.com/fibo/flow-view/blob/master/src/components/Frame.js#L551) methods.
