### ISSUE TITLE
Example page broken on Firefox.

### ISSUE THREAD

**Issue by davydka** [fibo/flow-view#48]
In Firefox, go to http://g14n.info/flow-view/example/
Observe CPU spikes, browser eventually asks to kill script. The console shows endless resize events firing.

Tested on Firefox 62, MacOS 10.13.6

**Comment by fibo** [comment]
Thank you very much for reporting it! I was using a `MutationObserver` but it looks like Firefox enters in a loop. Now I am using a good old `resize` event listener.

**Comment by fibo** [comment]
fixed on v3.0.1 patch release
