### ISSUE TITLE
How can I view the json output once I change the graph

### ISSUE THREAD

**Issue by mbaljeetsingh** [fibo/flow-view#58]
Hi,

I want to save the **json** state of the graph and then **load** it later. 

You have mentioned in the readme, we can use loadGraph method to load the json. Can you tell me the **method** I can use to see the current json of the graph (that I can save on button click)

Thanks

**Comment by fibo** [comment]
Ciao @mbaljeetsingh thank you very much for this hint!

Indeed there was no method yet, I added a [getGraph method](https://github.com/fibo/flow-view#getgraph).

It is released in current new version `v4.2.0` and you may want to take a look to [this demo file](https://github.com/fibo/flow-view/blob/master/demo.html) which implements a download button.

नमस्ते
