### ISSUE TITLE
Can we connect the node to itself

### ISSUE THREAD

**Issue by mbaljeetsingh** [fibo/flow-view#59]
Is it currently possible to connect the node to itself. Like connecting the **input** to the **output** of the same node.
![Capture](https://user-images.githubusercontent.com/872762/76724574-6dd71900-6771-11ea-8736-e3902acc9cef.GIF)

**Comment by fibo** [comment]
Nice question.

It should not be possible, in theory. For example I am copying a lot of ideas from [vvvv](https://vvvv.org/) and to do that in *vvvv* you need to use a special node called *FrameDelay*.

I will add a check to the library to avoid such loops.

**Comment by fibo** [comment]
@mbaljeetsingh I just released a `v4.2.1` that includes a check to avoid *self loops*.

**Comment by mbaljeetsingh** [comment]
Hi @fibo can you make it optional to have self loop. As I actually need to be able to create self loop.
Thanks

**Comment by fibo** [comment]
Yes it is possible, I am going to create another issue for that.

I do not know the timing, I am working on *flow-view* in my spare time.

I immagine a self loop as a circle or arc.

**Comment by mbaljeetsingh** [comment]
Hi @fibo 

Please take your time. Yes self loop is a circle or arc.
I'm currently connecting output of **incoming call** to input of **2** and output of **2** to input of **incoming call**
I think this will probably work for my case (fingers crossed). But the flow is not very clear. If we can have a arrow pointing to the different nodes with direction. That will be great. 

![Capture](https://user-images.githubusercontent.com/872762/76847645-66df0200-6868-11ea-9e5c-cf2059785abf.JPG)
