### ISSUE TITLE
Can we add Description to node along with Text

### ISSUE THREAD

**Issue by mbaljeetsingh** [fibo/flow-view#60]
Is there a way to add a **new property** to the  _**node**_ and show it in the **graph**. Le't's say if I want to add/show **description** along with the **Text(title)**
![Capture](https://user-images.githubusercontent.com/872762/76727623-8bf54700-677a-11ea-8bd5-fff1f1f6f8aa.JPG)

**Comment by fibo** [comment]
Hi @mbaljeetsingh yes it could be possible. Actually I am thinking *flow-view* to be extendable, and to be able to create custom nodes.

I am currently doing something similar in my other project https://github.com/fibo/dflow.it

For example, immagine you want a node with a 3d canvas inside, or a node with an audio wave, or also as you suggested, a node with a Textarea...

the *flow-view* API is thinked to be able to do that, currently I do not have a ready example. In my *dflow.it* project linked above, I started creating a *boolean* node.

So the answer is **yes** it should be possible by extending the FlowViewNode class. By now there is not a ready example, you can start have a look here https://github.com/fibo/dflow.it/blob/master/dflow-app.js

I think your idea is really good and I would like to create an example here in *flow-view* to show how to customize a node.

Can you add some more detail about the goal you want to achieve? So I could create an example that is as close as possible to what you are thinking about.

**Comment by mbaljeetsingh** [comment]
Hi @fibo 
I'm trying to build a **IVR** (interactive voice response) system. 
e.g. you can have a look at this **twilio studio** video https://youtu.be/GifYSpB-EU4
This is very similar to what I want to achieve.

I'm very close with flow view. Thanks for this amazing tool 😀

**Comment by fibo** [comment]
Thank you!

Your idea is a good example to be used to document how to create a custom node.

It would also like if we can add a link to your tool in flow-view documentation.

**Comment by fibo** [comment]
hi @mbaljeetsingh ,
 
it was recently added the possibility to create comment nodes so you can add as many descriptions you need. I hope this helps in your use case.

You may also want to see the [custom node example](https://github.com/fibo/flow-view/tree/main/examples/custom-node) so the description could be editable.

<img width="490" alt="Screenshot 2022-03-27 at 13 16 58" src="https://user-images.githubusercontent.com/176730/160279041-b8179286-0f23-48e8-8ef4-e3e687eb26f0.png">
