### ISSUE TITLE
Connecting the input to output of same node hides the link behind

### ISSUE THREAD

**Issue by mbaljeetsingh** [fibo/flow-view#63]
Hi @fibo 

I'm trying to connect the input to out for the same node. I have created a Test node. In the following image, you can see on the right the link is there but it is hiding behind the node.

![image](https://user-images.githubusercontent.com/872762/76855343-f1c6f900-6876-11ea-84c7-104d878bf00a.png)

**Comment by mbaljeetsingh** [comment]
I guess self connecting node with arc or circle will fix that.

**Comment by fibo** [comment]
I tryed is also and it was working, are you using latest version?

Anyway, I already opened an issue to implement self loops [here](https://github.com/fibo/flow-view/issues/61).

I am sorry about timing, right now I started a new job and I am quite busy, so I do not think I will have to time to work no this feature soon.

**Comment by mbaljeetsingh** [comment]
Hi Fibo

Yes, I'm using the latest version. 
Please take your time. 

Thanks

**Comment by fibo** [comment]
I am sorry, I thinked about it and I thought it is not worth to support loops. I will keep it as simple as possible.
