### ISSUE TITLE
Named input/output example

### ISSUE THREAD

**Issue by UksusoFF** [fibo/flow-view#65]
Can input/output have names? 
Seems it's implemented https://github.com/fibo/flow-view/issues/20 
Can you add example or improve documentation how it's can be used?

**Comment by fibo** [comment]
after latest major version I removed in/out name from [schema](https://github.com/fibo/flow-view/blob/master/schema.json) but it is a good idea to name them

**Comment by UksusoFF** [comment]
So it's possible on current version?

**Comment by fibo** [comment]
No, I am sorry, currently it is not possible

**Comment by fibo** [comment]
I am working on a rebranded version where ins/outs can have names, as well as many other features

**Comment by fibo** [comment]
inputs and outputs now can have names as well as custom text (see demo example https://github.com/fibo/flow-view/blob/main/index.html)
